/*
 * Generated by promo/tools/capture_guide.mjs. Don't edit it by hand: rerun
 *
 *   node promo/tools/capture_guide.mjs
 *
 * which rewrites this file and the PNGs in public/guide/. Rects are
 * [left, top, width, height] as fractions of each capture, measured off the
 * DOM. Radii and field metrics are in the page's CSS px; cssWidth is the
 * capture's width in those px.
 */

export const CAPTURES = {
  "home-top": {
    "image": "guide/home-top.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "hero": {
        "rect": [
          0.167,
          0.1074,
          0.3825,
          0.0969
        ],
        "radius": 16
      },
      "publish": {
        "rect": [
          0.167,
          0.2202,
          0.0938,
          0.0526
        ],
        "radius": 12
      },
      "youtubeRow": {
        "rect": [
          0.167,
          0.4134,
          0.3825,
          0.0988
        ],
        "radius": 12
      },
      "setUpPublishing": {
        "rect": [
          0.177,
          0.4754,
          0.0653,
          0.0206
        ],
        "radius": 4
      },
      "agentStatus": {
        "rect": [
          0.5654,
          0.7779,
          0.3326,
          0.0771
        ],
        "radius": 12
      }
    }
  },
  "home-agent": {
    "image": "guide/home-agent.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "agentStatus": {
        "rect": [
          0.5654,
          0.5523,
          0.3326,
          0.0771
        ],
        "radius": 12
      },
      "agentPanel": {
        "rect": [
          0.5654,
          0.6401,
          0.3326,
          0.2316
        ],
        "radius": 16
      },
      "download": {
        "rect": [
          0.5751,
          0.8073,
          0.1102,
          0.0526
        ],
        "radius": 12
      },
      "ffmpegLine": {
        "rect": [
          0.5876,
          0.7509,
          0.3008,
          0.0249
        ],
        "radius": 6
      },
      "agentNote": {
        "rect": [
          0.5674,
          0.8806,
          0.3286,
          0.0408
        ],
        "radius": 6
      }
    }
  },
  "pair-dialog": {
    "image": "guide/pair-dialog.png",
    "width": 1400,
    "height": 1143,
    "cssWidth": 700,
    "targets": {
      "card": {
        "rect": [
          0.1,
          0.105,
          0.8,
          0.79
        ],
        "radius": 16
      },
      "computer": {
        "rect": [
          0.7539,
          0.4188,
          0.0775,
          0.0381
        ],
        "radius": 4
      },
      "code": {
        "rect": [
          0.6514,
          0.508,
          0.18,
          0.0508
        ],
        "radius": 6
      },
      "pairIt": {
        "rect": [
          0.1457,
          0.6211,
          0.2143,
          0.0829
        ],
        "radius": 12
      }
    }
  },
  "paired": {
    "image": "guide/paired.png",
    "width": 1400,
    "height": 1143,
    "cssWidth": 700,
    "targets": {
      "card": {
        "rect": [
          0.1,
          0.2672,
          0.8,
          0.4656
        ],
        "radius": 16
      },
      "lead": {
        "rect": [
          0.1457,
          0.4407,
          0.7086,
          0.0761
        ],
        "radius": 6
      },
      "done": {
        "rect": [
          0.1457,
          0.5939,
          0.2143,
          0.0829
        ],
        "radius": 12
      }
    }
  },
  "preview-before": {
    "image": "guide/preview-before.png",
    "width": 516,
    "height": 920,
    "cssWidth": 258,
    "targets": {}
  },
  "preview-warning": {
    "image": "guide/preview-warning.png",
    "width": 1723,
    "height": 262,
    "cssWidth": 861.63,
    "targets": {}
  },
  "preview-after": {
    "image": "guide/preview-after.png",
    "width": 516,
    "height": 920,
    "cssWidth": 258,
    "targets": {}
  },
  "settings-subject": {
    "image": "guide/settings-subject.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "description": {
        "rect": [
          0.177,
          0.0887,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "searchTerms": {
        "rect": [
          0.177,
          0.2176,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "sources": {
        "rect": [
          0.177,
          0.4753,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "playlists": {
        "rect": [
          0.177,
          0.6659,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "channels": {
        "rect": [
          0.177,
          0.7947,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "line1": {
        "rect": [
          0.5405,
          0.3396,
          0.3575,
          0.0626
        ],
        "radius": 12
      },
      "line2": {
        "rect": [
          0.5405,
          0.4022,
          0.3575,
          0.0626
        ],
        "radius": 12
      },
      "line2Field": {
        "rect": [
          0.587,
          0.4173,
          0.301,
          0.0313
        ],
        "radius": 0,
        "field": {
          "inset": 1.6,
          "insetRight": 1.6,
          "padTop": 3.2,
          "fontSize": 15,
          "lineHeight": 21.75,
          "weight": 400,
          "color": "rgb(138, 135, 129)",
          "background": "rgb(19, 19, 22)",
          "align": "right",
          "valign": "center",
          "font": "sans"
        }
      },
      "save": {
        "rect": [
          0.8045,
          0.9427,
          0.0829,
          0.0455
        ],
        "radius": 12
      }
    }
  },
  "settings-showfilter": {
    "image": "guide/settings-showfilter.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "showMatch": {
        "rect": [
          0.167,
          0.0431,
          0.3575,
          0.0647
        ],
        "radius": 12
      },
      "showName": {
        "rect": [
          0.167,
          0.1078,
          0.3575,
          0.0626
        ],
        "radius": 12
      },
      "showNameField": {
        "rect": [
          0.2383,
          0.1229,
          0.2762,
          0.0313
        ],
        "radius": 0,
        "field": {
          "inset": 1.6,
          "insetRight": 1.6,
          "padTop": 3.2,
          "fontSize": 15,
          "lineHeight": 21.75,
          "weight": 400,
          "color": "rgb(138, 135, 129)",
          "background": "rgb(19, 19, 22)",
          "align": "right",
          "valign": "center",
          "font": "sans"
        }
      },
      "showTerms": {
        "rect": [
          0.177,
          0.2158,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "regulars": {
        "rect": [
          0.177,
          0.3447,
          0.3375,
          0.0608
        ],
        "radius": 16,
        "field": {
          "inset": 9.6,
          "insetRight": 9.6,
          "padTop": 7.2,
          "fontSize": 14.4,
          "lineHeight": 20.16,
          "weight": 400,
          "color": "rgb(244, 242, 239)",
          "background": "rgb(25, 25, 32)",
          "align": "left",
          "valign": "top",
          "font": "sans"
        }
      },
      "save": {
        "rect": [
          0.8045,
          0.9427,
          0.0829,
          0.0455
        ],
        "radius": 12
      }
    }
  },
  "settings-cut": {
    "image": "guide/settings-cut.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "clips": {
        "rect": [
          0.167,
          0.0424,
          0.3575,
          0.0626
        ],
        "radius": 12
      },
      "length": {
        "rect": [
          0.167,
          0.1049,
          0.3575,
          0.0626
        ],
        "radius": 12
      },
      "listen": {
        "rect": [
          0.167,
          0.7335,
          0.3575,
          0.0647
        ],
        "radius": 12
      },
      "aiPicks": {
        "rect": [
          0.167,
          0.7982,
          0.3575,
          0.0647
        ],
        "radius": 12
      },
      "save": {
        "rect": [
          0.8045,
          0.9427,
          0.0829,
          0.0455
        ],
        "radius": 12
      }
    }
  },
  "home-ready": {
    "image": "guide/home-ready.jpg",
    "width": 3200,
    "height": 1800,
    "cssWidth": 1600,
    "targets": {
      "hero": {
        "rect": [
          0.167,
          0.1074,
          0.3825,
          0.0969
        ],
        "radius": 16
      },
      "publish": {
        "rect": [
          0.167,
          0.2202,
          0.0938,
          0.0526
        ],
        "radius": 12
      },
      "youtubeRow": {
        "rect": [
          0.167,
          0.4134,
          0.3825,
          0.0782
        ],
        "radius": 12
      }
    }
  },
  "explorer-root": {
    "image": "guide/explorer-root.png",
    "width": 2364,
    "height": 1244,
    "cssWidth": 1182,
    "targets": {
      "ffmpeg": {
        "rect": [
          0.1548,
          0.3312,
          0.8342,
          0.0482
        ],
        "radius": 4
      },
      "readMe": {
        "rect": [
          0.1548,
          0.4277,
          0.8342,
          0.0482
        ],
        "radius": 4
      },
      "agent": {
        "rect": [
          0.1548,
          0.4759,
          0.8342,
          0.0482
        ],
        "radius": 4
      }
    }
  },
  "explorer-ffmpeg": {
    "image": "guide/explorer-ffmpeg.png",
    "width": 2364,
    "height": 1244,
    "cssWidth": 1182,
    "targets": {
      "ffmpegExe": {
        "rect": [
          0.1548,
          0.3312,
          0.8342,
          0.0482
        ],
        "radius": 4
      },
      "ffprobeExe": {
        "rect": [
          0.1548,
          0.3794,
          0.8342,
          0.0482
        ],
        "radius": 4
      }
    }
  }
} as const;
